//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto_Evaluaciones
    {
        public int Numero_Evaluacion { get; set; }
        public int Codigo_Proceso { get; set; }
        public string Codigo_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Logros { get; set; }
        public string Metas { get; set; }
        public string Estado_AE { get; set; }
        public Nullable<decimal> Nota_Final_AE { get; set; }
    }
}
