//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public string Codigo_Cargo { get; set; }
        public string Nombre_Cargo { get; set; }
        public string Fondo { get; set; }
        public string Ciclo { get; set; }
        public Nullable<int> IdState { get; set; }
    }
}
