//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_Usuarios
    {
        public string Codigo_Usuario { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public int Rut { get; set; }
        public string Fondo { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Termino_Contrato { get; set; }
        public string Calidad_Contrato { get; set; }
        public string Tipo_Contrato { get; set; }
        public string Codigo_Contrato { get; set; }
    }
}
