//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas_Cargos
    {
        public string Codigo_Cargo { get; set; }
        public string Cod_Cargo_Evaluado { get; set; }
        public string Codigo_seccion { get; set; }
        public int Numero_Pregunta { get; set; }
        public int IdState { get; set; }
    }
}
