//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Preguntas_Aleatorias
    {
        public string Codigo_Seccion { get; set; }
        public int Numero_Pregunta { get; set; }
        [DataType(DataType.MultilineText)]
        public string Texto_Pregunta { get; set; }
        public decimal Ponderacion_P { get; set; }
    }
}
