//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secciones
    {
        public int Id { get; set; }
        public string Codigo_Seccion { get; set; }
        public string Nombre_Seccion { get; set; }
        public decimal Ponderacion_S { get; set; }
        public int IdState { get; set; }
    }
}
