//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluacion360.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Codigo_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public int Tipo_Usuario { get; set; }
        public string Codigo_Cargo { get; set; }
        public string PASS { get; set; }
        public int IdState { get; set; }
    }
}
